name: Dev Branch Validation

# This runs automatically on dev branch pushes
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Quick validation test
      run: |
        echo "🔍 Running quick validation..."
        node validate-and-generate.js sample-config.json
        
    - name: Clean up
      run: |
        echo "🧹 Cleaning up generated frameworks..."
        rm -rf *-k6-framework *-performance-tests-k6-framework *-api-performance-tests-k6-framework
        echo "✅ Cleanup completed"
